# .travis.yml
dist: xenial

language: php

php:
  - 7.2

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor
before_install:
  - composer require --dev php-coveralls/php-coveralls
before_script:
  - cp .env.example .env
  - sudo mysql -e 'CREATE DATABASE laravel;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit --coverage-clover /tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
